Flask Web Application/website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import Admin, Applicant, InterviewVideo
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from .views import *
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        id = request.form.get('id')
        passsword = request.form.get('password')

        admin = Admin.query.filter_by(id=id).first()
        print(admin)
        if admin==None:
              flash('ID does not exist.', category='error')
        else:
            if check_password_hash(admin.password,passsword):
                flash('Logged in successfully!', category='success')
                login_user(admin, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')

    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET','POST'])
def sign_up():
    if request.method == 'POST':
        id = request.form.get('id')
        name = request.form.get('name')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        admin = Admin.query.filter_by(id=id).first()
        if admin:
            flash('ID already exists.', category='error')
        elif len(name) < 2:
            flash('name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_admin = Admin(id=id, name=name, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_admin)
            db.session.commit()
            login_user(new_admin, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

@auth.route('/add-applicant', methods=['GET','POST'])
def add_applicant():
    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        age = request.form.get('age')
        gender = request.form.get('gender')
        phone = request.form.get('phone')
        applicant = Applicant.query.filter_by(phone=phone).first()
        emailcheck=Applicant.query.filter_by(email=email).first()
        if applicant:
            flash('Phone number already exists.', category='error')
        elif emailcheck:
            flash('Email already exists.', category='error')    
        elif len(name) < 2:
            flash('name must be greater than 1 character.', category='error')
        elif len(phone) != 10:
            flash('phone must be 10 digits.', category='error')    
        else:
            new_applicant = Applicant(phone=phone, name=name, email=email, age=age,gender=gender)
            db.session.add(new_applicant)
            db.session.commit()
            flash('Applicant added!', category='success')
            return redirect(url_for('auth.add_applicant'))
    return render_template("add_applicant.html",data=[{'name':'male'}, {'name':'female'}], user=current_user)

@auth.route('/upload-interview', methods=['GET','POST'])
def upload_interview():
    if request.method == 'POST':
        file = request.files['file'] 
        nname= request.form.get('applicant')
        filename= file.filename
        file.save(os.path.join('interviews', filename))
        result = Applicant.query.filter_by(name=nname).first()
        
        new_interview = InterviewVideo(applicant_phone=result.phone, admin_id=current_user.id )
        db.session.add(new_interview)
        db.session.commit()
        videoToframes(new_interview.id)
        
    return render_template("upload_interview.html", user=current_user,query=Applicant.query.all())

@auth.route('/view-reports', methods=['GET','POST'])
def viewR():
    return render_template("viewR.html", user=current_user)

@auth.route('/view-applicants', methods=['GET','POST'])
def viewA():
    
        
    return render_template("viewA.html", user=current_user,query=Applicant.query.all())

@auth.route('/applicant-report', methods=['GET','POST'])
def report():
    return render_template("report.html", user=current_user)

Flask Web Application/website/templates/add_applicant.html
{% extends "base.html" %} {% block title %}Add Applicant{% endblock %} {% block content
    %}
    <h1 style="color:white; ">Welcome</h1>{{user.name}}
    <center>
        <div class="rectangle" style=" width:454px; height:701px">
            <div class="rec_item">
                <br>
                    
                    <h3>Add Applicant</h3>
                    <form method="POST">
                        <label >Name:</label>
                        <input type="text" id="name" name="name"><br><br>
                        <label >Email:</label>
                        <input type="email" id="email" name="email"><br><br>
                        <label for="age">Age:</label>
                          <input type="text" id="age" name="age"><br><br>
                          <label for="gender">Gender:</label>
                          <select id="gender" name="gender">
                            {% for o in data %}
              <option value="{{ o.name }}">{{ o.name }}</option>
              {% endfor %}
                              
                            </select><br><br>  
                            <label >Phone:</label>
                        <input type="text" id="phone" name="phone"><br><br>
                        <input type="submit" value="Add">
                </div>
     </div>
    </center>

{% endblock %}    

Flask Web Application/website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="..\static\style.css"/>

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg ">
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbar"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
          <div class="navbar-nav">
            {% if user.is_authenticated%}  
            <a class="nav-item nav-link" id="home" href="/">Home</a>
           
            <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
            {% else %}
            <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
            <a class="nav-item nav-link" id="login" href="/login">Login</a>
            {% endif %}

          </div>
        </div>
      </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <script
    src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"
  ></script>

  <script
    type="text/javascript"
    src="{{ url_for('static', filename='index.js') }}"
  ></script>
  </body>
</html>

Flask Web Application/website/templates/home.html
{% extends "base.html" %}
{% block title%}Home{% endblock %}
{% block content %}

<h1 style="color:white; ">Welcome</h1>{{user.name}}
<center>


<div class="rectangle"style="top:100px">
 
    <div class="rec_item">
    <br>
    <a href="/add-applicant">
        <img src="..\static\add_applicant.jpg" width="200px" height="200px">
        <h3>Add Applicant</h3>
    </a>
    </div>
    <div class="rec_item">
        <br>
        <a href="/view-applicants">
        <img src="..\static\view_applicant.jpg" width="200px" height="200px">
        <h3>View Applicant</h3>
        </a>
    </div>
    <div class="rec_item">
        <br>
        <a href="/upload-interview">
        <img src="..\static\upload_interview.jpg" width="200px" height="200px">
        <h3>Upload Interview</h3>
        </a>
    </div>  
    <div class="rec_item">
        <br>
        <a href="/view-reports">
        <img src="..\static\view_reports.jpg" width="200px" height="200px">
        <h3>View Reports</h3>
        </a>
    </div>
   
  </div>
</center>
        {% endblock %}

Flask Web Application/website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
  %}
  <center>
        
    <div class="rectangle" style="top:100px; width:454px; height:536px">
     
        <div class="rec_item">
        <br>
            
            <h3>Login</h3>
            <form method="POST">
                <label for="id">ID:</label>
                <input type="text" id="id" name="id" placeholder="Enter ID"><br><br>
                <label for="password">Password:</label>
                <input type="password" id="pass" name="password" placeholder="Enter password"><br><br>
                <button type="submit" class="btn btn-primary btn-lg btn-block">Login</button>
              </form>
        </div>
      </div>
      {% for mesg in get_flashed_messages() %}
     <h5>{{ mesg }}</h5>
     {% endfor %}
    </center>
  {% endblock %}

Flask Web Application/website/templates/report.html
{% extends "base.html" %} {% block title %}View Reports{% endblock %} {% block content
    %}
<style>
    html,
    body {
      width: 100vw;
      height: 100vh;
    }
    
    div {
      width: 100%;
      height: 100%
    }
    
    body {
      padding: 0;
      margin: 0;
      width: 100vw;
      height: 100vh;
      background: linear-gradient(to right,
          #52A6E3 0%,
          #52A6E3 50%,
          #DBEEFF 50%,
          #DBEEFF 100%);
    }
    
    .rectangle {
      position: relative;
      width: 60%;
      height: 650px;
      background-color: white;
      border-radius: 50px;
      display: grid;
      grid-template-columns: auto auto auto auto;
      margin-top: 5%;
      margin-bottom: 5%;
    }
    
    .rectangle h3 {
      color: #1187DD;
      font-size: 32px;
      font-family: 'Inter';
    }
    
    .rec_box {
      box-sizing: border-box;
      position: absolute;
      width: 38%;
      height: auto;
      border: 2px solid #52A6E3;
      border-radius: 16px;
      margin: 5px;
    }
    
    .rec_box p {
      position: relative;
      font-size: 20px;
      text-align: left;
      left: 30px;
      color: #0062A9;
    }
</style>

    <body>
        <h1 style="color:white; top:10px; right:10px;">Welcome</h1>
        
        <center>
            <div class="rectangle">
                <h3>Applicant's Report</h3>

                <div>
                <div class="rec_box" style="left: 10%; top:15%;">
                    <p>Name:</p>
                </div>
                <div class="rec_box" style="left: 10%; top:30%; bottom: 13%;">
                    <p>image</p>
                </div>

                
                <div class="rec_box" style="right: 10%; top:15%;">
                    <p>Openness:</p>
                </div>
                <div class="rec_box" style="right: 10%; top:30%;">
                    <p>Conscientiousness:</p>
                </div>
                <div class="rec_box" style="right: 10%; top:45%;">
                    <p>Extraversion:</p>
                </div>
                <div class="rec_box" style="right: 10%; top:60%;">
                    <p>Agreeableness:</p>
                </div>
                <div class="rec_box" style="right: 10%; top:75%;">
                    <p>Neuroticism:</p>
                </div>
            </div>

            </div>

        </center>
    </body>
    {% endblock %} 

Flask Web Application/website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
    content %}
    <center>
        
      <div class="rectangle" style="top:100px; width:454px; height:536px">
       
          <div class="rec_item">
          <br>
          
    <form method="POST">
      <h3 align="center">Sign Up</h3>
      <div class="form-group">
        <label for="id">ID</label>
        <input
          type="id"
          class="form-control"
          id="id"
          name="id"
          placeholder="Enter ID"
        />
      </div>
      <div class="form-group">
        <label for="name">Name</label>
        <input
          type="text"
          class="form-control"
          id="name"
          name="name"
          placeholder="Enter first name"
        />
      </div>
      <div class="form-group">
        <label for="password1">Password</label>
        <input
          type="password"
          class="form-control"
          id="password1"
          name="password1"
          placeholder="Enter password"
        />
      </div>
      <div class="form-group">
        <label for="password2">Password (Confirm)</label>
        <input
          type="password"
          class="form-control"
          id="password2"
          name="password2"
          placeholder="Confirm password"
        />
      </div>
      
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>

</div>
{% for mesg in get_flashed_messages() %}
     <h5>{{ mesg }}</h5>
     {% endfor %}
<center>
{% endblock %}

Flask Web Application/website/templates/upload_interview.html
{% extends "base.html" %} {% block title %}Upload Interview{% endblock %} {% block content
    %}
    <h1 style="color:white; ">Welcome</h1>{{user.name}}
    <center>
        <div class="rectangle" style=" width:656px; height:511px">
            <div class="rec_item">
                <br>
                <h3>Upload Interview</h3>
                <br>
                
                <form method="POST" action="{{ url_for('auth.upload_interview') }}" enctype="multipart/form-data">
                   
                    <label for="img">Choose Applicant:</label>
                    
                    <select id="applicant" name="applicant" >
                        {%for o in query%}
                        <option value="{{o.name}}">{{o.name}}</option>
                        {%endfor%}
                    </select><br><br>
                    
                    <label >Select File:</label>
                    <input type="file" id="file" name="file" accept="video/*"><br>
                    <br>
                    <input type="submit">
                  </form>
            </div>
        </div>
    </center>

{% endblock %}    

Flask Web Application/website/templates/viewA.html
{% extends "base.html" %} {% block title %}View Applicants{% endblock %} {% block content
    %}

<style>
  html,
  body {
    width: 100vw;
    height: 100vh;
  }
  
  div {
    width: 100%;
    height: 100%
  }
  
  body {
    padding: 0;
    margin: 0;
    width: 100vw;
    height: 100vh;
    background: linear-gradient(to right,
        #52A6E3 0%,
        #52A6E3 50%,
        #DBEEFF 50%,
        #DBEEFF 100%);
  }
  
  .rectangle {
    position: relative;
    width: 60%;
    height: 650px;
    background-color: white;
    border-radius: 50px;
    display: grid;
    grid-template-columns: auto auto auto auto;
    margin-top: 5%;
    margin-bottom: 5%;
  }
  
  .rectangle h3 {
    color: #1187DD;
    font-size: 32px;
  }
  
  .rec_box {
    position: absolute;
    width: 80%;
    height: auto;
    border: 2px solid #52A6E3;
    border-radius: 16px;
    margin: 5px;
    left: 10%;
    top: 15%;
    text-align: left;
    float: left;
    color: #0062A9;
    font-size: 20px;
  }
  .text {
    margin-left :10%;
  }
  button{
    background-color:#1187DD;
    color:white;
    font-size: 19px;
    text-align: center;
    border-radius: 10px;
    padding-left:3%;
    padding-right:3%;
    float: right;
    margin-right:10%;
    cursor: pointer;
    border: 1px solid;
  }
  button:hover {
    background-color: white;
    color:#1187DD;
  }
</style>

<body>
   <h1 style="color:white; top:10px; right:10px;">Welcome</h1>{{user.name}}

   <center>
       <div class="rectangle">
           <h3>View Applicants</h3>
             
           <div class="rec_box">  
            {%for o in query%}  
               <p class="text">
                {{o.name}}
                   <button>Edit</button>
                   <br>
                   {%endfor%}
               </p>
               
           </div>
       </div>
   </center>

{% endblock %}  

Flask Web Application/website/templates/viewR.html
{% extends "base.html" %} {% block title %}View Reports{% endblock %} {% block content
    %}
<style>
    html,
    body {
      width: 100vw;
      height: 100vh;
    }
    
    div {
      width: 100%;
      height: 100%
    }
    
    body {
      padding: 0;
      margin: 0;
      width: 100vw;
      height: 100vh;
      background: linear-gradient(to right,
          #52A6E3 0%,
          #52A6E3 50%,
          #DBEEFF 50%,
          #DBEEFF 100%);
    }
    
    .rectangle {
      position: relative;
      width: 60%;
      height: 650px;
      background-color: white;
      border-radius: 50px;
      display: grid;
      grid-template-columns: auto auto auto auto;
      margin-top: 5%;
      margin-bottom: 5%;
    }
    
    .rectangle h3 {
      color: #1187DD;
      font-size: 32px;
    
    }
    
    .rec_box {
      /* box-sizing: border-box; */
      position: absolute;
      width: 80%;
      height: auto;
      border: 2px solid #52A6E3;
      border-radius: 16px;
      margin: 5px;
      left: 10%;
      top: 30%;
      text-align: left;
      float: left;
      color: #0062A9;
      font-size: 20px;
    }
    
    .rec_small {
      box-sizing: border-box;
      position: absolute;
      width: 9%;
      height: auto;
      border: 2px solid #52A6E3;
      color: #0062A9;
      border-radius: 10px;
      float: left;
      text-align: left;
      font-size: 20px;
    }
    
    .text {
      padding-left: 5%;
      float: left;
    }
    
    .sort {
      position: absolute;
      margin: 5px;
      left: 10%;
      top: 15%;
    }
    
    .sort p {
      font-size: 140%;
      text-align: left;
      color: #0062A9;
    }
    
    .sort select {
      color: #0062A9;
      background-color: white;
      text-align: left;
      font-size: 20px;
      border-radius: 11px;
      border: 2px solid #1187DD;
    }
</style>

<body>
    <h1 style="color:white; top:10px; right:10px;">Welcome</h1>{{user.name}}

    <center>
        <div class="rectangle">
            <h3>View Reports</h3>
            <div class="sort">
                <p>Sort by:
                    <select>
                        <option>Openness</option>
                        <option>Conscientiousness</option>
                        <option>Extraversion</option>
                        <option>Agreeableness</option>
                        <option>Neuroticism</option>
                    </select>
                </p>
            </div>

            <div class="rec_box">
                <a class="text" href="/applicant-report">Name</a>
                <p class="rec_small" style="left:50%;">O:</p>
                <p class="rec_small" style="left:60%;">C:</p>
                <p class="rec_small" style="left:70%;">E:</p>
                <p class="rec_small" style="left:80%;">A:</p>
                <p class="rec_small" style="left:90%;">N:</p>
            </div>

        </div>

    </center>
</body>
{% endblock %} 